### ISSUE TITLE
memory refactor - spiled and program_end

### ISSUE THREAD

**Issue by ppisa** [hollmmax/QtMips#6]
I like actual series of memory refactor work patches and I plan to expose it to the public in the CVUT QtMips main repository in the branch "devel" for now.

I have found two issues.

1. SPILED peripheral endianness seems to be incorrect for both big-endian and little-endian targets, i.e. seems reversed.
2. all internal examples stops after the first instruction thanks to the condition if (regs->read_pc() >= program_end). program_end seems not to be set when machine starts empty. Generally, I am not sure if we want  program_end aka program.end() at all. Initial idea was that when ELF is loaded then when end of the .text section is reached, execution ends. We have better control by break instruction or exit syscall now. Even C compiled ELF file can build trampolines on stack or in heap allocated memory. When emulator run in start empty mode, then program_end is zero now. No such thing exists on real CPU, it usually happily interprets values reads from memory mapped peripherals as instructions. It is even sometimes abused by interrupt controller etc. So one option is to get rid of mechanisms all together or set program.end() to start of peripherals regions 0xffff0000 for actual 32-bits targets.

Please resolve these two details, include last temporary typo correction into series, ideally check the middle steps compile and then we save the reached level in main QtMips devel branch. Please start to think about intended directory structure for pushing QtRvSim repo.

Thanks,

Pavel Pisa

**Comment by jdupak** [comment]
SPILED now works correctly - there has been wrong setting.
Default program end is now 0xffff0000.
Typo commits were rebased.

All commits should be atomic now, tests. I have tested tests and gui after each.
